services:
  api:
    build:
      context: .
      dockerfile: EnergyControlAPI/Dockerfile
    user: "${UID}:${GID}"
    environment:
      # String de conexão para SQLite. O arquivo .db será salvo no diretório /app/data
      - ConnectionStrings__DatabaseConnection=Data Source=/app/data/energycontrol.db
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # Monta o volume 'sqlitedata' no diretório /app/data dentro do contêiner
      # Isso garante que o arquivo do banco de dados persista
      - sqlitedata:/app/data

volumes:
  sqlitedata: # Volume para persistir o arquivo do banco de dados SQLite

networks:
  default:
    driver: bridge